ALTER TABLE THT_CK_22_CUSTOMERS
DROP CONSTRAINT FK_THT_CK_22_MBID;
ALTER TABLE THT_CK_23_EMPLOYEES
DROP CONSTRAINT FK_THT_CK_23_EMP; -- Trương Hồng Thái

DROP TABLE THT_CK_68_DISPOSAL_DETAILS;
DROP TABLE THT_CK_67_DISPOSAL_NOTE;
DROP TABLE THT_CK_66_GD_DETAILS;
DROP TABLE THT_CK_65_GOODS_DELIVERY;
DROP TABLE THT_CK_64_GD_REASONS;
DROP TABLE THT_CK_63_GR_DETAILS;
DROP TABLE THT_CK_62_GOODS_RECEIPT;
DROP TABLE THT_CK_61_GR_REASONS;

DROP TABLE THT_CK_57_PAYROLLS;
DROP TABLE THT_CK_56_TIMESHEETS;
DROP TABLE THT_CK_55_HANDOVER_SLIPS;
DROP TABLE THT_CK_54_ASSIGN;
DROP TABLE THT_CK_53_POSITIONS;
DROP TABLE THT_CK_52_SHIFTS;
DROP TABLE THT_CK_51_CONTRACTS;

DROP TABLE THT_CK_44_USE_POINTS;
DROP TABLE THT_CK_43_ADD_POINTS;
DROP TABLE THT_CK_42_MEMBER_CARD;
DROP TABLE THT_CK_41_MEMBER_TYPES;

DROP TABLE THT_CK_35_BRANCH_INV_PROMO;
DROP TABLE THT_CK_34_INV_PROMO;
DROP TABLE THT_CK_33_BRANCH_ITEM_PROMO;
DROP TABLE THT_CK_32_ITEM_PROMO_DETAILS;
DROP TABLE THT_CK_31_ITEM_PROMO;

DROP TABLE THT_CK_29_RETURN_DETAILS;
DROP TABLE THT_CK_28_PRODUCT_RETURN;
DROP TABLE THT_CK_27_PAYMENT_DETAILS;
DROP TABLE THT_CK_26_PAYMENT_METHODS;
DROP TABLE THT_CK_25_INVOICE_DETAILS;
DROP TABLE THT_CK_24_INVOICES;
DROP TABLE THT_CK_23_EMPLOYEES;
DROP TABLE THT_CK_22_CUSTOMERS;
DROP TABLE THT_CK_21_ACCOUNTS;

DROP TABLE THT_CK_18_PRICE_HISTORY;
DROP TABLE THT_CK_17_CURENT_STOCKS;
DROP TABLE THT_CK_16_PRODUCTS;
DROP TABLE THT_CK_15_CATEGORIES;
DROP TABLE THT_CK_14_SUPPLIERS;
DROP TABLE THT_CK_13_STORAGE;
DROP TABLE THT_CK_12_BRANCHES;
DROP TABLE THT_CK_11_LOCATION_TYPES;


CREATE TABLE THT_CK_11_LOCATION_TYPES (
    LOC_TYPE_ID CHAR(4) PRIMARY KEY,
    NAME VARCHAR2(50)
);

CREATE TABLE THT_CK_12_BRANCHES (
    BRANCH_ID NUMBER(10) PRIMARY KEY,
    ADDRESS VARCHAR2(50),
    AREA FLOAT DEFAULT 0,
    LOC_TYPE_ID CHAR(4) NOT NULL
        REFERENCES THT_CK_11_LOCATION_TYPES(LOC_TYPE_ID)
);

CREATE TABLE THT_CK_13_STORAGE (
    STORAGE_ID NUMBER(10) PRIMARY KEY,
    ADDRESS VARCHAR2(50),
    BRANCH_ID NUMBER(10) NOT NULL
        REFERENCES THT_CK_12_BRANCHES(BRANCH_ID)
);

CREATE TABLE THT_CK_14_SUPPLIERS (
    SUPPLIER_ID NUMBER(10) PRIMARY KEY,
    SUPPLIER_NAME VARCHAR2(50) NOT NULL,
    PHONE VARCHAR2(15),
    ADDRESS VARCHAR2(50)
);

CREATE TABLE THT_CK_15_CATEGORIES (
    CATEGORY_ID NUMBER(10) PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(50) NOT NULL
);

CREATE TABLE THT_CK_16_PRODUCTS (
    PRODUCT_ID NUMBER(10) PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(50) NOT NULL,
    UNIT VARCHAR2(10) NOT NULL,
    CATEGORY_ID NUMBER(10) NOT NULL
        REFERENCES THT_CK_15_CATEGORIES(CATEGORY_ID),
    SUPPLIER_ID NUMBER(10) NOT NULL
        REFERENCES THT_CK_14_SUPPLIERS(SUPPLIER_ID)
);

CREATE TABLE THT_CK_17_CURENT_STOCKS (
    PRODUCT_ID NUMBER(10),
    STORAGE_ID NUMBER(10),
    SELL_PRICE FLOAT DEFAULT 0,
    DISCOUNT FLOAT DEFAULT 0,
    GET_PROD_ID NUMBER(10),
    QUANTITY FLOAT DEFAULT 0,
    "MAP" FLOAT DEFAULT 0,
    UPDATE_ON DATE,
    PRIMARY KEY (PRODUCT_ID, STORAGE_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES THT_CK_16_PRODUCTS(PRODUCT_ID),
    FOREIGN KEY (STORAGE_ID) REFERENCES THT_CK_13_STORAGE(STORAGE_ID),
    FOREIGN KEY (GET_PROD_ID) REFERENCES THT_CK_16_PRODUCTS(PRODUCT_ID)
);

CREATE TABLE THT_CK_18_PRICE_HISTORY (
    STORAGE_ID NUMBER(10),
    PRODUCT_ID NUMBER(10),
    APPLIED_DATE DATE, -- CREATE TRIGGER TO TRUNC DATE-ELIMINATE TIME~~~
    SELL_PRICE FLOAT DEFAULT 0,
    DISCOUNT FLOAT DEFAULT 0,
    GET_PROD_ID NUMBER(10), -- NO REF, SAVE HISTORY ONLY
    PROMO_CODE VARCHAR2(30),
    UPDATE_ON DATE,
    PRIMARY KEY (STORAGE_ID, PRODUCT_ID, APPLIED_DATE),
    FOREIGN KEY (STORAGE_ID) REFERENCES THT_CK_13_STORAGE(STORAGE_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES THT_CK_16_PRODUCTS(PRODUCT_ID)
);

----------------------------------------------------------

CREATE TABLE THT_CK_21_ACCOUNTS (
    ACCOUNT_ID VARCHAR2(30) PRIMARY KEY,
    "PASSWORD" VARCHAR2(50) NOT NULL,
    LAST_MODIFY DATE
);

CREATE TABLE THT_CK_22_CUSTOMERS (
    CUSTOMER_ID NUMBER(10) PRIMARY KEY,
    "NAME" VARCHAR2(50) NOT NULL,
    DOB DATE,
    PHONE VARCHAR2(15),
    EMAIL VARCHAR2(50),
    MEMBER_TYPE VARCHAR2(20),
    ACCOUNT_ID VARCHAR2(30) NOT NULL REFERENCES THT_CK_21_ACCOUNTS(ACCOUNT_ID),
    MEMBER_CARD_ID NUMBER(10) -- ALTER4 NOT DONE
);

CREATE TABLE THT_CK_23_EMPLOYEES (
    EMPLOYEE_ID NUMBER(10) PRIMARY KEY,
    "NAME" VARCHAR2(50) NOT NULL,
    DOB DATE,
    PHONE VARCHAR2(15),
    ADDRESS VARCHAR2(50),
    CONTRACT_ID NUMBER(10) -- ALTER5 NOT DONE
);

CREATE TABLE THT_CK_24_INVOICES (
    INVOICE_NO NUMBER(10) PRIMARY KEY,
    "DATE" DATE NOT NULL,
    TOTAL_AMOUNT FLOAT DEFAULT 0,
    TOTAL_ITEM_DISCOUNT FLOAT DEFAULT 0,
    ORDER_DISCOUNT FLOAT DEFAULT 0,
    AMOUNT_TB_PAID FLOAT DEFAULT 0,
    BRANCH_ID NUMBER(10) NOT NULL REFERENCES THT_CK_12_BRANCHES(BRANCH_ID),
    EMPLOYEE_ID NUMBER(10) NOT NULL REFERENCES THT_CK_23_EMPLOYEES(EMPLOYEE_ID),
    CUSTOMER_ID NUMBER(10) REFERENCES THT_CK_22_CUSTOMERS(CUSTOMER_ID),
    PROMO_CODE VARCHAR2(30) --ALTER3 NOT DONE
);

CREATE TABLE THT_CK_25_INVOICE_DETAILS (
    INVOICE_NO NUMBER(10) NOT NULL REFERENCES THT_CK_24_INVOICES(INVOICE_NO),
    PRODUCT_ID NUMBER(10) NOT NULL REFERENCES THT_CK_16_PRODUCTS(PRODUCT_ID),
    PRIMARY KEY (INVOICE_NO, PRODUCT_ID),
    QUANTITY FLOAT DEFAULT 0,
    SELL_PRICE FLOAT DEFAULT 0,
    DISCOUNT FLOAT DEFAULT 0,
    AMOUNT FLOAT DEFAULT 0
);

CREATE TABLE THT_CK_26_PAYMENT_METHODS (
    METHOD_ID NUMBER(10) PRIMARY KEY,
    METHOD_NAME VARCHAR2(50) NOT NULL
);

CREATE TABLE THT_CK_27_PAYMENT_DETAILS (
    INVOICE_NO NUMBER(10) NOT NULL REFERENCES THT_CK_24_INVOICES(INVOICE_NO),
    METHOD_ID NUMBER(10) NOT NULL REFERENCES THT_CK_26_PAYMENT_METHODS(METHOD_ID),
    PRIMARY KEY (INVOICE_NO, METHOD_ID),
    AMOUNT FLOAT DEFAULT 0
);

CREATE TABLE THT_CK_28_PRODUCT_RETURN (
    RETURN_NO NUMBER(10) PRIMARY KEY,
    "DATE" DATE,
    EMPLOYEE_ID NOT NULL REFERENCES THT_CK_23_EMPLOYEES(EMPLOYEE_ID),
    TOTAL_QUANTITY FLOAT DEFAULT 0,
    TOTAL_PAID_AMOUNT FLOAT DEFAULT 0
);

CREATE TABLE THT_CK_29_RETURN_DETAILS (
    INVOICE_NO NUMBER(10) NOT NULL REFERENCES THT_CK_24_INVOICES(INVOICE_NO),
    RETURN_NO NUMBER(10) NOT NULL REFERENCES THT_CK_28_PRODUCT_RETURN(RETURN_NO),
    PRODUCT_ID NUMBER(10) NOT NULL,
    QUANTITY FLOAT DEFAULT 0,
    DISCOUNT FLOAT DEFAULT 0,
    PAID_AMOUNT FLOAT DEFAULT 0,
    
    PRIMARY KEY(INVOICE_NO, RETURN_NO, PRODUCT_ID)
);
------------------------------------------

CREATE TABLE THT_CK_31_ITEM_PROMO (
    PROMO_CODE VARCHAR2(30) PRIMARY KEY,
    START_DATE DATE NOT NULL,
    END_DATE DATE
);

CREATE TABLE THT_CK_32_ITEM_PROMO_DETAILS (
    PROMO_CODE VARCHAR2(30) NOT NULL REFERENCES THT_CK_31_ITEM_PROMO(PROMO_CODE),
    BUY_PROD_ID NUMBER(10) NOT NULL REFERENCES THT_CK_16_PRODUCTS(PRODUCT_ID),
    DISCOUNT FLOAT,
    GET_PROD_ID NUMBER(10) REFERENCES THT_CK_16_PRODUCTS(PRODUCT_ID),
    PRIMARY KEY (PROMO_CODE, BUY_PROD_ID),
    CONSTRAINT CHECK_NULL_PROMO_32
        CHECK ((DISCOUNT IS NULL AND GET_PROD_ID IS NOT NULL)
            OR (DISCOUNT IS NOT NULL AND GET_PROD_ID IS NULL))    
);

CREATE TABLE THT_CK_33_BRANCH_ITEM_PROMO (
    PROMO_CODE VARCHAR2(30) NOT NULL REFERENCES THT_CK_31_ITEM_PROMO(PROMO_CODE),
    BRANCH_ID NUMBER(10) NOT NULL REFERENCES THT_CK_12_BRANCHES(BRANCH_ID),
    PRIMARY KEY (PROMO_CODE, BRANCH_ID)
);

CREATE TABLE THT_CK_34_INV_PROMO (
    PROMO_CODE VARCHAR2(30) PRIMARY KEY,
    INV_AMOUNT FLOAT DEFAULT 0,
    DISCOUNT FLOAT,
    GET_PROD_ID NUMBER(10) REFERENCES THT_CK_16_PRODUCTS(PRODUCT_ID),
    START_DATE DATE NOT NULL,
    END_DATE DATE,
    CONSTRAINT CHECK_NULL_PROMO_34
        CHECK ((DISCOUNT IS NULL AND GET_PROD_ID IS NOT NULL)
            OR (DISCOUNT IS NOT NULL AND GET_PROD_ID IS NULL))
);

CREATE TABLE THT_CK_35_BRANCH_INV_PROMO (
    PROMO_CODE VARCHAR2(30) NOT NULL REFERENCES THT_CK_34_INV_PROMO(PROMO_CODE),
    BRANCH_ID NUMBER(10) NOT NULL REFERENCES THT_CK_12_BRANCHES(BRANCH_ID),
    PRIMARY KEY (PROMO_CODE, BRANCH_ID)
);
------------------------------------------

CREATE TABLE THT_CK_41_MEMBER_TYPES (
    TYPE_ID NUMBER(4) PRIMARY KEY,
    "NAME" VARCHAR2(50) NOT NULL,
    MIN_POINT NUMBER(10) NOT NULL,
    MAX_POINT NUMBER(10) NOT NULL,
    SHORT_DESC VARCHAR2(50),
    LONG_DESC VARCHAR2(500)
);

CREATE TABLE THT_CK_42_MEMBER_CARD (
    MEMBER_CARD_ID NUMBER(10) PRIMARY KEY,
    CURRENT_POINTS NUMBER(10),
    ACCUMULATED_POINTS NUMBER(10),
    TYPE_ID NUMBER(4) NOT NULL REFERENCES THT_CK_41_MEMBER_TYPES(TYPE_ID) 
);
--ALTER4 DONE
ALTER TABLE THT_CK_22_CUSTOMERS
ADD CONSTRAINT FK_THT_CK_22_MBID FOREIGN KEY (MEMBER_CARD_ID)
    REFERENCES THT_CK_42_MEMBER_CARD(MEMBER_CARD_ID);

CREATE TABLE THT_CK_43_ADD_POINTS (
    INVOICE_NO NUMBER(10) NOT NULL REFERENCES THT_CK_24_INVOICES(INVOICE_NO),
    CUSTOMER_ID NUMBER(10) NOT NULL REFERENCES THT_CK_22_CUSTOMERS(CUSTOMER_ID),
    POINTS NUMBER(10) NOT NULL,
    PRIMARY KEY (INVOICE_NO, CUSTOMER_ID)
);

CREATE TABLE THT_CK_44_USE_POINTS (
    INVOICE_NO NUMBER(10) NOT NULL REFERENCES THT_CK_24_INVOICES(INVOICE_NO),
    CUSTOMER_ID NUMBER(10) NOT NULL REFERENCES THT_CK_22_CUSTOMERS(CUSTOMER_ID),
    POINTS NUMBER(10) NOT NULL,
    PRIMARY KEY (INVOICE_NO, CUSTOMER_ID)
);

CREATE TABLE THT_CK_51_CONTRACTS(
    CONTRACT_ID NUMBER(10) PRIMARY KEY,
    EMPLOYEE_ID NUMBER(10) NOT NULL,
    CONTRACT_TYPE VARCHAR2(20),
    SALARY FLOAT DEFAULT 0,
    EFFECTIVE_DATE DATE NOT NULL,
    EXP_DATE DATE
);
--ALTER5
ALTER TABLE THT_CK_23_EMPLOYEES
ADD CONSTRAINT FK_THT_CK_23_EMP FOREIGN KEY (CONTRACT_ID)
    REFERENCES THT_CK_51_CONTRACTS(CONTRACT_ID);

CREATE TABLE THT_CK_52_SHIFTS(
    SHIFT_ID NUMBER(2) PRIMARY KEY,
    SHIFT_NAME VARCHAR2(10) NOT NULL,
    START_TIME CHAR(4) DEFAULT '0000',
    END_TIME CHAR(4) DEFAULT '0000'
);

CREATE TABLE THT_CK_53_POSITIONS(
    POSITION_ID NUMBER(10) PRIMARY KEY,
    POSITION_NAME VARCHAR2(30) NOT NULL
);

CREATE TABLE THT_CK_54_ASSIGN(
    ASSIGN_ID NUMBER(10) PRIMARY KEY,
    EMPLOYEE_ID NUMBER(10) NOT NULL
        REFERENCES THT_CK_23_EMPLOYEES(EMPLOYEE_ID),
    BRANCH_ID NUMBER(10) NOT NULL
        REFERENCES THT_CK_12_BRANCHES(BRANCH_ID),
    POSITION_ID NUMBER(10) NOT NULL
        REFERENCES THT_CK_53_POSITIONS(POSITION_ID),
    START_DATE DATE NOT NULL,
    END_DATE DATE
);

CREATE TABLE THT_CK_55_HANDOVER_SLIPS(
    SLIP_NO NUMBER(10) PRIMARY KEY,
    SHIFT_ID NUMBER(2) NOT NULL
        REFERENCES THT_CK_52_SHIFTS(SHIFT_ID),
    HANDOVER_EMP NUMBER(10) NOT NULL
        REFERENCES THT_CK_23_EMPLOYEES(EMPLOYEE_ID),
    RECEIVE_EMP NUMBER(10) NOT NULL
        REFERENCES THT_CK_23_EMPLOYEES(EMPLOYEE_ID),
    BRANCH_ID NUMBER(10) NOT NULL
        REFERENCES THT_CK_12_BRANCHES(BRANCH_ID),
    "DATE" DATE NOT NULL,
    OPENNING_BALANCE FLOAT DEFAULT 0,
    ENDING_BALANCE FLOAT DEFAULT 0
);

CREATE TABLE THT_CK_56_TIMESHEETS(
    EMPLOYEE_ID NUMBER(10)
        REFERENCES THT_CK_23_EMPLOYEES(EMPLOYEE_ID),
    SHIFT_ID NUMBER(2)
        REFERENCES THT_CK_52_SHIFTS(SHIFT_ID),
    "DATE" DATE,
    PRIMARY KEY (EMPLOYEE_ID, SHIFT_ID, "DATE"),
    
    TIME_IN CHAR(4),
    TIME_OUT CHAR(4),
    WORK_HOURS FLOAT DEFAULT 0,
    OVER_TIME FLOAT DEFAULT 0,
    BRANCH_ID NUMBER(10) NOT NULL
        REFERENCES THT_CK_12_BRANCHES(BRANCH_ID),
    "PERIOD" VARCHAR2(20) NOT NULL
);

CREATE TABLE THT_CK_57_PAYROLLS(
    PAYROLL_NO NUMBER(10) PRIMARY KEY,
    EMPLOYEE_ID NUMBER(10) NOT NULL
        REFERENCES THT_CK_23_EMPLOYEES(EMPLOYEE_ID),
    "PERIOD" VARCHAR2(20) NOT NULL,
    CONTRACT_SALARY FLOAT DEFAULT 0,
    WORKING_DAYS FLOAT DEFAULT 0,
    WORKING_SALARY FLOAT DEFAULT 0,
    ALLOWANCE FLOAT DEFAULT 0,
    BONUS FLOAT DEFAULT 0,
    TOTAL FLOAT DEFAULT 0
);

CREATE TABLE THT_CK_61_GR_REASONS(
    GR_TYPE_ID NUMBER(4) PRIMARY KEY,
    "DESCRIPTION" VARCHAR2(50)
);

CREATE TABLE THT_CK_62_GOODS_RECEIPT(
    GR_NO NUMBER(10) PRIMARY KEY,
    "DATE" DATE,
    TOTAL_QUANTITY FLOAT DEFAULT 0,
    REFERENCE_NO NUMBER(10),
    GR_TYPE_ID NUMBER(4)
        REFERENCES THT_CK_61_GR_REASONS(GR_TYPE_ID),
    EMPLOYEE_ID NUMBER(10)
        REFERENCES THT_CK_23_EMPLOYEES(EMPLOYEE_ID),
    STORAGE_ID NUMBER(10)
        REFERENCES THT_CK_13_STORAGE(STORAGE_ID)
);

CREATE TABLE THT_CK_63_GR_DETAILS(
    DETAIL_ID NUMBER(4),
    GR_NO NUMBER(10)
        REFERENCES THT_CK_62_GOODS_RECEIPT(GR_NO),
    PRODUCT_ID NUMBER(10)
        REFERENCES THT_CK_16_PRODUCTS(PRODUCT_ID),
    PRIMARY KEY (DETAIL_ID, GR_NO, PRODUCT_ID),
    
    LOT VARCHAR2(20),
    PRICE FLOAT DEFAULT 0,
    QUANTITY FLOAT DEFAULT 0,
    EXP_DATE DATE,
    GOODS_CONDITION VARCHAR2(20),
    CONSTRAINT UNQ_GR_DETAILS UNIQUE(GR_NO, PRODUCT_ID, LOT)
);

CREATE TABLE THT_CK_64_GD_REASONS(
    GD_TYPE_ID NUMBER(4) PRIMARY KEY,
    "DESCRIPTION" VARCHAR2(50)
);

CREATE TABLE THT_CK_65_GOODS_DELIVERY(
    GD_NO NUMBER(10) PRIMARY KEY,
    "DATE" DATE,
    TOTAL_QUANTITY FLOAT DEFAULT 0,
    REFERENCE_NO NUMBER(10),
    GD_TYPE_ID NUMBER(4)
        REFERENCES THT_CK_64_GD_REASONS(GD_TYPE_ID),
    EMPLOYEE_ID NUMBER(10)
        REFERENCES THT_CK_23_EMPLOYEES(EMPLOYEE_ID),
    STORAGE_ID NUMBER(10)
        REFERENCES THT_CK_13_STORAGE(STORAGE_ID)
);

CREATE TABLE THT_CK_66_GD_DETAILS(
    DETAIL_ID NUMBER(4),
    GD_NO NUMBER(10)
        REFERENCES THT_CK_65_GOODS_DELIVERY(GD_NO),
    PRODUCT_ID NUMBER(10)
        REFERENCES THT_CK_16_PRODUCTS(PRODUCT_ID),
    PRIMARY KEY (DETAIL_ID, GD_NO, PRODUCT_ID),
    
    LOT VARCHAR2(20),
    PRICE FLOAT DEFAULT 0,
    QUANTITY FLOAT DEFAULT 0,
    EXP_DATE DATE,
    GOODS_CONDITION VARCHAR2(20),
    CONSTRAINT UNQ_GD_DETAILS UNIQUE(GD_NO, PRODUCT_ID, LOT)
);

CREATE TABLE THT_CK_67_DISPOSAL_NOTE(
    DISPOSAL_NO NUMBER(10) PRIMARY KEY,
    "DATE" DATE,
    TOTAL_QUANTITY FLOAT DEFAULT 0,
    EMPLOYEE_ID NUMBER(10)
        REFERENCES THT_CK_23_EMPLOYEES(EMPLOYEE_ID),
    STORAGE_ID NUMBER(10)
        REFERENCES THT_CK_13_STORAGE(STORAGE_ID)
);

CREATE TABLE THT_CK_68_DISPOSAL_DETAILS(
    DETAIL_ID NUMBER(4),
    DISPOSAL_NO NUMBER(10)
        REFERENCES THT_CK_67_DISPOSAL_NOTE(DISPOSAL_NO),
    PRODUCT_ID NUMBER(10)
        REFERENCES THT_CK_16_PRODUCTS(PRODUCT_ID),
    PRIMARY KEY (DETAIL_ID, DISPOSAL_NO, PRODUCT_ID),
    LOT VARCHAR2(20),
    QUANTITY FLOAT DEFAULT 0,
    REASON VARCHAR2(50),
    CONSTRAINT UNQ_DISPOSAL_DETAILS UNIQUE(DISPOSAL_NO, PRODUCT_ID, LOT)
);
